// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorDto } from "../shared/AuthorDto";

/**
 * A comment with its author.
 */
export type CommentDto = { id: string; article_id: string; author: AuthorDto; content: string; created_at: string };
