// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /api/articles/{slug}/comments`.
 */
export type CreateCommentRequest = { content: string, };
