// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `DELETE /api/admin/users/{id}/comments`.
 */
export type DeletedCommentsDto = { 
/**
 * Number of comments deleted.
 */
deleted: number, };
