// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public identity of the author of an article or a comment.
 */
export type AuthorDto = { id: string, username: string, };
