// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable machine-readable error codes.
 */
export type ErrorCode = "validation_error" | "not_found" | "unauthorized" | "forbidden" | "conflict" | "internal_error";
