// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * JSON body of every error response.
 */
export type ErrorBody = { error: ErrorCode, 
/**
 * Human-readable message.
 */
message: string, 
/**
 * Per-field messages, only for validation errors.
 */
fields?: { [key in string]: Array<string> }, };
