// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination query string (`?page=2&per_page=10`).
 */
export type PageQuery = { page?: number | null, per_page?: number | null, };
