// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A page of items plus the metadata needed to render a paginator.
 */
export type Paginated<T> = { items: Array<T>, total: number, page: number, per_page: number, total_pages: number, };
