// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /api/cv`.
 */
export type DownloadResumeRequest = { 
/**
 * Response of the captcha widget (Cloudflare Turnstile).
 */
captcha_token: string, };
