// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query string of the public article listing.
 */
export type ArticlesQuery = { page?: number | null; per_page?: number | null; category?: string | null };
