// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorDto } from "../shared/AuthorDto";
import type { CategoryDto } from "./CategoryDto";

/**
 * A full article, including its Markdown body.
 */
export type ArticleDto = { content: string, id: string, title: string, slug: string, excerpt: string | null, cover_image: string | null, author: AuthorDto, category: CategoryDto, reading_time_minutes: number, is_published: boolean, comments_enabled: boolean, published_at: string | null, created_at: string, updated_at: string, };
