// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body used to create or update an article.
 */
export type UpsertArticleRequest = { category_id: string, title: string, 
/**
 * Derived from the title on creation when empty; kept as-is on update when empty.
 */
slug?: string | null, excerpt?: string | null, 
/**
 * Markdown body.
 */
content: string, 
/**
 * `true` to make the article public.
 */
publish: boolean, };
