// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body used to create or update a category.
 */
export type UpsertCategoryRequest = {
  name: string;
  /**
   * Derived from the name when empty.
   */
  slug?: string | null;
  description?: string | null;
};
