// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserDto } from "./UserDto";

/**
 * Returned after a successful registration or login.
 */
export type AuthResponse = { 
/**
 * JWT to send as `Authorization: Bearer <token>`.
 */
token: string, expires_at: string, user: UserDto, };
