// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /api/admin/users/{id}/ban`.
 */
export type BanUserRequest = { 
/**
 * Optional reason, shown in the dashboard and to the banned user at login.
 */
reason?: string | null, };
