// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime settings of the Identity context (`GET /api/settings/identity`).
 */
export type IdentitySettingsDto = { 
/**
 * Whether visitors can create an account.
 */
registration_enabled: boolean, };
