// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `POST /api/auth/register`.
 */
export type RegisterRequest = { username: string, email: string, password: string, 
/**
 * Response of the captcha widget (Cloudflare Turnstile).
 */
captcha_token: string, };
