// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleDto } from "./RoleDto";

/**
 * Private view of an account (current user, administration).
 */
export type UserDto = { id: string; username: string; email: string; role: RoleDto; created_at: string };
